apiVersion: v1
kind: Pod
metadata:
  name: gpu-smoke
  namespace: gpu-jobs
spec:
  restartPolicy: Never
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  nodeSelector:
    workload: gpu
  containers:
  - name: sleep
    image: public.ecr.aws/docker/library/busybox:1.36
    command: ["sh","-c","echo hello && sleep 3600"]
    resources:
      limits:
        nvidia.com/gpu: 1
